spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://121.36.25.96:33060/core?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      username: P1cGFkH2YE
      password: r85yQGiz6i
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 10
