server:
  port: 13792
  servlet:
    context-path: '/${spring.application.name}'
  tomcat:
    connection-timeout: 180000
spring:
  application:
    name: jarvins-backend
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://jarvins.com:33060/jarvins?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      username: P1cGFkH2YE
      password: r85yQGiz6i
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 15
  redis:
    host: jarvins.com
    password: yKE6kABJee
    port: 36379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    path: '/jarvins/jarvins-backend/logs/${spring.application.name}'
