server:
  port: 10000
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
